site_name: 'My Wiki'
site_description: ''
site_author: ''
site_url: ''

copyright: ''

theme:
  name: 'material'
  custom_dir: overrides/
  palette:
    primary: '546E7A'
    accent: '546E7A'
  font: false
  logo: ''
  favicon: ''
#extra:
#  social:
#  - type: ''
#    link: ''
#  manifest: ''
extra_javascript:
- js/mathjax.js
- 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
- 'https://cdn.jsdelivr.net/npm/mermaid@10.4.0/dist/mermaid.min.js'
extra_css:
- css/extra.css
markdown_extensions:
- footnotes
- pymdownx.arithmatex
- pymdownx.details
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.extra
- pymdownx.superfences:
    preserve_tabs: true
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_div_format
- admonition
- pymdownx.highlight:
    guess_lang: false
    use_pygments: false
- toc:
    permalink: true
plugins:
  - search
  - exclude:
      glob:
        - node_modules/*
        - "*.pdf"
        - "*.gz"
        - "*.py"
        - "*.pyc"
      regex:
        - '.*\.(bin|tar)$'

nav:
